-- ⚠️  MOVED — this file is no longer maintained.
--
-- The single canonical database schema now lives at:
--     src/lib/schema.sql
--
-- It is fully idempotent (CREATE TABLE IF NOT EXISTS + ALTER … ADD COLUMN
-- IF NOT EXISTS + guarded policies). Run THAT file in the Supabase SQL
-- editor to create or update the database. Keeping two schema files in
-- sync caused drift (e.g. the sermons.youtube_url column), so this copy
-- was intentionally emptied.
